# Generated by Django 6.0.3 on 2026-03-26 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_client_remove_report_contractor_remove_report_tower_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Project Site', 'verbose_name_plural': 'Project Sites'},
        ),
    ]
