# Generated by Django 6.0.3 on 2026-03-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Contractor', 'Contractor'), ('QA', 'QA')], default='Client', max_length=20),
        ),
    ]
