# Generated by Django 6.0.3 on 2026-03-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_site_options_rename_qa_notes_report_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('not_visited', 'Not Visited'), ('visit_in_progress', 'Visit In Progress'), ('site_data_submitted', 'Site Data Submitted'), ('qa_validation', 'QA Validation'), ('engineer_review', 'Engineer Review'), ('submitted', 'Submitted')], default='not_visited', max_length=30),
        ),
    ]
