# Generated by Django 6.0.3 on 2026-03-27 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='site_photos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Validation'), ('APPROVED', 'Approved'), ('REJECTED', 'Rework Required')], default='PENDING', max_length=20)),
                ('qa_feedback', models.TextField(blank=True, help_text='Reason for rework if rejected.', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(limit_choices_to={'groups__name': 'Contractors'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reports.site')),
            ],
        ),
    ]
