# Generated by Django 6.0.3 on 2026-03-27 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_sitephoto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('alert_type', models.CharField(choices=[('CHECK_IN', 'Contractor Checked In'), ('UPLOAD', 'Photos Uploaded'), ('REWORK', 'Rework Requested')], default='CHECK_IN', max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_alerts', to='reports.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
