# Generated by Django 6.0.3 on 2026-03-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_activityalert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='contractor',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='final_document',
            field=models.FileField(blank=True, null=True, upload_to='final_reports/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='activityalert',
            name='alert_type',
            field=models.CharField(choices=[('CHECK_IN', 'Contractor Checked In'), ('UPLOAD', 'Photos/Reports Uploaded'), ('REWORK', 'Rework Requested')], default='CHECK_IN', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client'), ('Contractor', 'Contractor'), ('QA', 'QA'), ('Tech Writer', 'Technical Report Writer')], default='Client', max_length=50),
        ),
    ]
