# Generated by Django 5.1.4 on 2026-04-06 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_report_contractor_client_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('General', 'General Maintenance'), ('Post-Disaster', 'Post-Disaster Emergency Response')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='require_photo_minimums',
            field=models.BooleanField(default=False, help_text='Enforce minimum photo counts per category for contractors.'),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_repair_timeline',
            field=models.CharField(blank=True, help_text='AI Estimated time to fix', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ai_resource_suggestion',
            field=models.TextField(blank=True, help_text='AI Recommended crew size and equipment', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='equipment_damage_score',
            field=models.IntegerField(blank=True, help_text='AI Generated: 1-10 (Damage to antennas/cabling)', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='structural_risk_score',
            field=models.IntegerField(blank=True, help_text='AI Generated: 1-10 (10 being imminent failure)', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='urgency_flag',
            field=models.CharField(choices=[('Low', 'Defer Action'), ('Medium', 'Routine Maintenance'), ('High', 'Immediate Repair')], default='Low', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='criticality_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High Priority Node')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='ai_tags',
            field=models.CharField(blank=True, help_text='Comma separated AI tags (e.g., tilted mast, rust, snapped cable)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='category',
            field=models.CharField(choices=[('Site Overview', 'Site Overview (Min: 4)'), ('Access Road', 'Access Road (Min: 2)'), ('Tower Structure', 'Tower Structure (Min: 5)'), ('Tower Base & Foundation', 'Tower Base & Foundation (Min: 14)'), ('Antennas & Mounting Systems', 'Antennas & Mounting Systems (Min: 9)'), ('Cabling & Connections', 'Cabling & Connections (Min: 3)'), ('Equipment Shelter / Cabinets', 'Equipment Shelter / Cabinets (Min: 2)'), ('Power Systems', 'Power Systems (Min: 2)'), ('Grounding & Earthing', 'Grounding & Earthing (Min: 2)'), ('Perimeter, Security & Surroundings', 'Perimeter, Security & Surroundings (Min: 5)'), ('Additional Observations', 'Additional Observations (Optional)')], default='Site Overview', max_length=100),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='contractor_notes',
            field=models.TextField(blank=True, help_text='Notes from the contractor.', null=True),
        ),
        migrations.AlterField(
            model_name='activityalert',
            name='alert_type',
            field=models.CharField(choices=[('CHECK_IN', 'Contractor Checked In'), ('UPLOAD', 'Photos/Reports Uploaded'), ('REWORK', 'Rework Requested'), ('AI_ALERT', 'AI Critical Risk Detected')], default='CHECK_IN', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('not_visited', 'Not Visited'), ('visit_in_progress', 'Visit In Progress'), ('qa_validation', 'QA Validation'), ('site_data_submitted', 'Site Data Submitted'), ('engineer_review', 'Report in Progress'), ('submitted', 'Submitted')], default='not_visited', max_length=30),
        ),
        migrations.CreateModel(
            name='SiteIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], default='Minor', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='reports.site')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
