# Generated by Django 5.1.4 on 2026-04-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_project_project_type_project_require_photo_minimums_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gemini Vision Prompt', max_length=100)),
                ('prompt_text', models.TextField(help_text='The exact instructions given to Gemini. WARNING: You MUST instruct it to return the exact JSON keys expected by the database!')),
                ('is_active', models.BooleanField(default=True, help_text='Check this to use this prompt. (Only the first active prompt will be used).')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Prompt Setting',
                'verbose_name_plural': 'AI Prompt Settings',
            },
        ),
    ]
