# Generated by Django 5.1.4 on 2026-04-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_aipromptsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category_damage_breakdown',
            field=models.TextField(blank=True, help_text='AI breakdown of equipment damage per category.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='client_executive_summary',
            field=models.TextField(blank=True, help_text='AI-generated high-level summary for the client dashboard.', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='historical_trend_analysis',
            field=models.TextField(blank=True, help_text='AI comparison of current vs past damages.', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='height_in_meters',
            field=models.FloatField(blank=True, help_text='Site height in meters', null=True),
        ),
    ]
