# Generated by Django 5.1.4 on 2026-04-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_category_damage_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='predictive_risk_outlook',
            field=models.TextField(blank=True, help_text='AI simulation of future structural degradation based on environment.', null=True),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='annotated_image',
            field=models.ImageField(blank=True, help_text='AI-drawn bounding boxes of damage.', null=True, upload_to='annotated_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sitephoto',
            name='is_drone_capture',
            field=models.BooleanField(default=False, help_text='True if uploaded via the Automated Drone API.'),
        ),
        migrations.AlterField(
            model_name='aipromptsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aipromptsettings',
            name='prompt_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_repair_timeline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ai_resource_suggestion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='category_damage_breakdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_executive_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='equipment_damage_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='historical_trend_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='structural_risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitephoto',
            name='ai_tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitephoto',
            name='contractor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitephoto',
            name='qa_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
