# Generated by Django 5.1.4 on 2026-04-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_report_predictive_risk_outlook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='drone_3d_model_link',
            field=models.URLField(blank=True, help_text='Public share link from DroneDeploy or Pix4D.', max_length=500, null=True),
        ),
    ]
