# Generated by Django 5.1.4 on 2026-04-07 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_report_drone_3d_model_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck this to instantly revoke drone access for this contractor.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.OneToOneField(limit_choices_to={'groups__name': 'Contractors'}, on_delete=django.db.models.deletion.CASCADE, related_name='drone_api_key', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
