# Generated by Django 5.1.4 on 2026-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_droneapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='support_tickets/%Y/%m/%d/'),
        ),
    ]
