# Generated by Django 5.1.4 on 2026-04-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_supportticket_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
