# Generated by Django 5.1.4 on 2026-04-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_userprofile_has_seen_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='welcome_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
