# Generated by Django 5.1.4 on 2026-04-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_userprofile_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='expected_antenna_count',
            field=models.IntegerField(blank=True, help_text='Total number of antennas the client expects on site', null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='expected_azimuth',
            field=models.CharField(blank=True, help_text='e.g., Sector A: 120°, Sector B: 240°', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='expected_tilt',
            field=models.CharField(blank=True, help_text='e.g., 4° downtilt on all sectors', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='sector_layout',
            field=models.CharField(blank=True, help_text='e.g., 3 Sectors, Huawei AAU panels', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='tower_type',
            field=models.CharField(blank=True, help_text='e.g., Monopole, Lattice, Guyed Mast, Rooftop', max_length=100, null=True),
        ),
    ]
