# Generated by Django 5.1.4 on 2026-04-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_site_expected_antenna_count_site_expected_azimuth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='min_access_road',
            field=models.IntegerField(default=2, verbose_name='Min Access Road'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_additional',
            field=models.IntegerField(default=0, verbose_name='Min Additional Observations'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_antennas',
            field=models.IntegerField(default=9, verbose_name='Min Antennas & Mounting'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_cabling',
            field=models.IntegerField(default=3, verbose_name='Min Cabling & Connections'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_equipment_shelter',
            field=models.IntegerField(default=2, verbose_name='Min Equipment Shelter'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_grounding',
            field=models.IntegerField(default=2, verbose_name='Min Grounding'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_perimeter',
            field=models.IntegerField(default=5, verbose_name='Min Perimeter & Security'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_power_systems',
            field=models.IntegerField(default=2, verbose_name='Min Power Systems'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_site_overview',
            field=models.IntegerField(default=4, verbose_name='Min Site Overview'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_tower_base',
            field=models.IntegerField(default=14, verbose_name='Min Tower Base & Foundation'),
        ),
        migrations.AddField(
            model_name='project',
            name='min_tower_structure',
            field=models.IntegerField(default=5, verbose_name='Min Tower Structure'),
        ),
    ]
