# Generated by Django 5.1.4 on 2026-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_project_min_access_road_project_min_additional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
