# Generated by Django 5.1.4 on 2026-04-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='min_access_road',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_additional',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_antennas',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_cabling',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_equipment_shelter',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_grounding',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_perimeter',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_power_systems',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_site_overview',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_tower_base',
        ),
        migrations.RemoveField(
            model_name='project',
            name='min_tower_structure',
        ),
        migrations.RemoveField(
            model_name='project',
            name='require_photo_minimums',
        ),
        migrations.AddField(
            model_name='report',
            name='min_access_road',
            field=models.IntegerField(default=2, verbose_name='Min Access Road'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_additional',
            field=models.IntegerField(default=0, verbose_name='Min Additional Observations'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_antennas',
            field=models.IntegerField(default=9, verbose_name='Min Antennas & Mounting'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_cabling',
            field=models.IntegerField(default=3, verbose_name='Min Cabling & Connections'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_equipment_shelter',
            field=models.IntegerField(default=2, verbose_name='Min Equipment Shelter'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_grounding',
            field=models.IntegerField(default=2, verbose_name='Min Grounding'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_perimeter',
            field=models.IntegerField(default=5, verbose_name='Min Perimeter & Security'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_power_systems',
            field=models.IntegerField(default=2, verbose_name='Min Power Systems'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_site_overview',
            field=models.IntegerField(default=4, verbose_name='Min Site Overview'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_tower_base',
            field=models.IntegerField(default=14, verbose_name='Min Tower Base & Foundation'),
        ),
        migrations.AddField(
            model_name='report',
            name='min_tower_structure',
            field=models.IntegerField(default=5, verbose_name='Min Tower Structure'),
        ),
        migrations.AddField(
            model_name='report',
            name='require_photo_minimums',
            field=models.BooleanField(default=False, help_text='Enforce minimum photo counts per category for contractors on this site visit.'),
        ),
    ]
